### ISSUE TITLE
Badge endpoint is no longer serving images

### ISSUE THREAD

**Issue by maxxxxxdlp** [specifysystems/sp_network#48]
https://broker.spcoco.org/api/v1/badge/?provider=gbif

![Screenshot 2023-03-22 at 09 56 21](https://user-images.githubusercontent.com/40512816/226944959-b3875f8c-3221-4d70-8ba7-856cd606a6e1.png)

Expected to see an image. Saw JSON instead

**Comment by zzeppozz** [comment]
Fixed in the new version, next to deploy as production

**Comment by zzeppozz** [comment]
Closed in PR #56
