### ISSUE TITLE
Very poor performance for /api/v1/occ/ endpoint

### ISSUE THREAD

**Issue by maxpatiiuk** [specifysystems/sp_network#58]
something is wrong with the new deployment
requests take half a minute to resolve

Example URL: https://broker.spcoco.org/api/v1/occ/?occid=db8cc0df-1ed3-11e3-bfac-90b11c41863e&provider=gbif

![Screenshot 2023-04-19 at 13 36 07](https://user-images.githubusercontent.com/40512816/233168733-770090d5-0979-46da-bee6-5ad6c2bdeb22.png)

**Comment by zzeppozz** [comment]
This URL points to the old deployment.  If the new one tests well, I will replace it soon.
