### ISSUE TITLE
bug: GBIF OCC returns 502

### ISSUE THREAD

**Issue by maxpatiiuk** [specifysystems/sp_network#98]
The following error returns a 502 error after a while: https://broker.spcoco.org/api/v1/occ/?occid=dc6f802f-1ed3-11e3-bfac-90b11c41863e&provider=gbif

**Comment by zzeppozz** [comment]
I was unable to recreate this error by just refreshing the page.  How did you get it?  I have now updated the previously-under-provisioned EC2 instance for the broker, so if it was resource-related, it may be solved.

**Comment by maxpatiiuk** [comment]
The request was originally made by specify 7, but the issue was happening even if I send it directly.
It's possible that this was a temporary occurrence - will close for now, unless it happens again.
